# Generated by Django 6.0.1 on 2026-01-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_w', models.IntegerField(help_text='Consommation en Watts')),
                ('is_essential', models.BooleanField(default=False, help_text='Est-ce un appareil indispensable ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_percent', models.IntegerField(help_text='Niveau de batterie en %')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity_ah', models.IntegerField(help_text='Capacité de la batterie en Ah')),
                ('panel_power_w', models.IntegerField(help_text='Puissance des panneaux en Watts')),
                ('system_voltage', models.IntegerField(choices=[(12, '12V'), (24, '24V')], default=12)),
                ('inverter_power_w', models.IntegerField(blank=True, help_text="Puissance de l'onduleur en Watts", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_system', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
